import type { App } from 'vue';
import Provider from './Provider.vue';
import FormatBold from './FormatBold.vue';
import FormatItalic from './FormatItalic.vue';
import FormatQuoteClose from './FormatQuoteClose.vue';
import LinkVariant from './LinkVariant.vue';
import FileImage from './FileImage.vue';
import Table from './Table.vue';
import FormatListNumbers from './FormatListNumbers.vue';
import FormatListBulleted from './FormatListBulleted.vue';
import FormatSize from './FormatSize.vue';
import FormatStrikethrough from './FormatStrikethrough.vue';
import StatusBar from './StatusBar.vue';
import NavigationBar from './NavigationBar.vue';
import SidePreview from './SidePreview.vue';
import Eye from './Eye.vue';
import Settings from './Settings.vue';
import FilePlus from './FilePlus.vue';
import FileMultiple from './FileMultiple.vue';
import FolderPlus from './FolderPlus.vue';
import Delete from './Delete.vue';
import Close from './Close.vue';
import Pen from './Pen.vue';
import Target from './Target.vue';
import ArrowLeft from './ArrowLeft.vue';
import HelpCircle from './HelpCircle.vue';
import Toc from './Toc.vue';
import Login from './Login.vue';
import Logout from './Logout.vue';
import Sync from './Sync.vue';
import SyncOff from './SyncOff.vue';
import Upload from './Upload.vue';
import ViewList from './ViewList.vue';
import Download from './Download.vue';
import CodeTags from './CodeTags.vue';
import CodeBraces from './CodeBraces.vue';
import OpenInNew from './OpenInNew.vue';
import Information from './Information.vue';
import Alert from './Alert.vue';
import SignalOff from './SignalOff.vue';
import Folder from './Folder.vue';
import ScrollSync from './ScrollSync.vue';
import Printer from './Printer.vue';
import Undo from './Undo.vue';
import Redo from './Redo.vue';
import ContentSave from './ContentSave.vue';
import Message from './Message.vue';
import History from './History.vue';
import Database from './Database.vue';
import Magnify from './Magnify.vue';
import FormatListChecks from './FormatListChecks.vue';
import CheckCircle from './CheckCircle.vue';
import ContentCopy from './ContentCopy.vue';
import Key from './Key.vue';
import DotsHorizontal from './DotsHorizontal.vue';
import Seal from './Seal.vue';
import ChevronUp from './ChevronUp.vue';
import ChevronDown from './ChevronDown.vue';
import LanguageMarkdown from './LanguageMarkdown.vue';
import LanguageHtml5 from './LanguageHtml5.vue';
import Math_ from './Math.vue';
import Sitemap from './Sitemap.vue';
import HorizontalRule from './HorizontalRule.vue';
import Marker from './Marker.vue';
import Footnote from './Footnote.vue';
import FormatSubscript from './FormatSubscript.vue';
import FormatSuperscript from './FormatSuperscript.vue';
import CodeInline from './CodeInline.vue';
import MusicNote from './MusicNote.vue';
import AutoFix from './AutoFix.vue';
import Calendar from './Calendar.vue';
import CaseSensitiveAlt from './CaseSensitiveAlt.vue';
import SortAlphabetical from './SortAlphabetical.vue';
import Omega from './Omega.vue';
import LinkBracket from './LinkBracket.vue';
import LinkPaste from './LinkPaste.vue';
import Frontmatter from './Frontmatter.vue';

// Registered on the app instance (Vue 3) instead of the old global
// Vue.component(). Used via app.use() in src/index.js.
export default {
  install(app: App) {
    app.component('iconProvider', Provider);
    app.component('iconFormatBold', FormatBold);
    app.component('iconFormatItalic', FormatItalic);
    app.component('iconFormatQuoteClose', FormatQuoteClose);
    app.component('iconLinkVariant', LinkVariant);
    app.component('iconFileImage', FileImage);
    app.component('iconTable', Table);
    app.component('iconFormatListNumbers', FormatListNumbers);
    app.component('iconFormatListBulleted', FormatListBulleted);
    app.component('iconFormatSize', FormatSize);
    app.component('iconFormatStrikethrough', FormatStrikethrough);
    app.component('iconStatusBar', StatusBar);
    app.component('iconNavigationBar', NavigationBar);
    app.component('iconSidePreview', SidePreview);
    app.component('iconEye', Eye);
    app.component('iconSettings', Settings);
    app.component('iconFilePlus', FilePlus);
    app.component('iconFileMultiple', FileMultiple);
    app.component('iconFolderPlus', FolderPlus);
    app.component('iconDelete', Delete);
    app.component('iconClose', Close);
    app.component('iconPen', Pen);
    app.component('iconTarget', Target);
    app.component('iconArrowLeft', ArrowLeft);
    app.component('iconHelpCircle', HelpCircle);
    app.component('iconToc', Toc);
    app.component('iconLogin', Login);
    app.component('iconLogout', Logout);
    app.component('iconSync', Sync);
    app.component('iconSyncOff', SyncOff);
    app.component('iconUpload', Upload);
    app.component('iconViewList', ViewList);
    app.component('iconDownload', Download);
    app.component('iconCodeTags', CodeTags);
    app.component('iconCodeBraces', CodeBraces);
    app.component('iconOpenInNew', OpenInNew);
    app.component('iconInformation', Information);
    app.component('iconAlert', Alert);
    app.component('iconSignalOff', SignalOff);
    app.component('iconFolder', Folder);
    app.component('iconScrollSync', ScrollSync);
    app.component('iconPrinter', Printer);
    app.component('iconUndo', Undo);
    app.component('iconRedo', Redo);
    app.component('iconContentSave', ContentSave);
    app.component('iconMessage', Message);
    app.component('iconHistory', History);
    app.component('iconDatabase', Database);
    app.component('iconMagnify', Magnify);
    app.component('iconFormatListChecks', FormatListChecks);
    app.component('iconCheckCircle', CheckCircle);
    app.component('iconContentCopy', ContentCopy);
    app.component('iconKey', Key);
    app.component('iconDotsHorizontal', DotsHorizontal);
    app.component('iconSeal', Seal);
    app.component('iconChevronUp', ChevronUp);
    app.component('iconChevronDown', ChevronDown);
    app.component('iconLanguageMarkdown', LanguageMarkdown);
    app.component('iconLanguageHtml5', LanguageHtml5);
    app.component('iconMath', Math_);
    app.component('iconSitemap', Sitemap);
    app.component('iconHorizontalRule', HorizontalRule);
    app.component('iconMarker', Marker);
    app.component('iconFootnote', Footnote);
    app.component('iconFormatSubscript', FormatSubscript);
    app.component('iconFormatSuperscript', FormatSuperscript);
    app.component('iconCodeInline', CodeInline);
    app.component('iconMusicNote', MusicNote);
    app.component('iconAutoFix', AutoFix);
    app.component('iconCalendar', Calendar);
    app.component('iconCaseSensitiveAlt', CaseSensitiveAlt);
    app.component('iconSortAlphabetical', SortAlphabetical);
    app.component('iconOmega', Omega);
    app.component('iconLinkBracket', LinkBracket);
    app.component('iconLinkPaste', LinkPaste);
    app.component('iconFrontmatter', Frontmatter);
  },
};
