import Provider from './Provider';
import FormatBold from './FormatBold';
import FormatItalic from './FormatItalic';
import FormatQuoteClose from './FormatQuoteClose';
import LinkVariant from './LinkVariant';
import FileImage from './FileImage';
import Table from './Table';
import FormatListNumbers from './FormatListNumbers';
import FormatListBulleted from './FormatListBulleted';
import FormatSize from './FormatSize';
import FormatStrikethrough from './FormatStrikethrough';
import StatusBar from './StatusBar';
import NavigationBar from './NavigationBar';
import SidePreview from './SidePreview';
import Eye from './Eye';
import Settings from './Settings';
import FilePlus from './FilePlus';
import FileMultiple from './FileMultiple';
import FolderPlus from './FolderPlus';
import Delete from './Delete';
import Close from './Close';
import Pen from './Pen';
import Target from './Target';
import ArrowLeft from './ArrowLeft';
import HelpCircle from './HelpCircle';
import Toc from './Toc';
import Login from './Login';
import Logout from './Logout';
import Sync from './Sync';
import SyncOff from './SyncOff';
import Upload from './Upload';
import ViewList from './ViewList';
import Download from './Download';
import CodeTags from './CodeTags';
import CodeBraces from './CodeBraces';
import OpenInNew from './OpenInNew';
import Information from './Information';
import Alert from './Alert';
import SignalOff from './SignalOff';
import Folder from './Folder';
import ScrollSync from './ScrollSync';
import Printer from './Printer';
import Undo from './Undo';
import Redo from './Redo';
import ContentSave from './ContentSave';
import Message from './Message';
import History from './History';
import Database from './Database';
import Magnify from './Magnify';
import FormatListChecks from './FormatListChecks';
import CheckCircle from './CheckCircle';
import ContentCopy from './ContentCopy';
import Key from './Key';
import DotsHorizontal from './DotsHorizontal';
import Seal from './Seal';
import ChevronUp from './ChevronUp';
import ChevronDown from './ChevronDown';
import LanguageMarkdown from './LanguageMarkdown';
import LanguageHtml5 from './LanguageHtml5';
import Math_ from './Math';
import Sitemap from './Sitemap';
import HorizontalRule from './HorizontalRule';
import Marker from './Marker';
import Footnote from './Footnote';
import FormatSubscript from './FormatSubscript';
import FormatSuperscript from './FormatSuperscript';
import CodeInline from './CodeInline';
import MusicNote from './MusicNote';
import AutoFix from './AutoFix';
import Calendar from './Calendar';
import CaseSensitiveAlt from './CaseSensitiveAlt';
import SortAlphabetical from './SortAlphabetical';
import Omega from './Omega';
import LinkBracket from './LinkBracket';
import LinkPaste from './LinkPaste';
import Frontmatter from './Frontmatter';

// Registered on the app instance (Vue 3) instead of the old global
// Vue.component(). Used via app.use() in src/index.js.
export default {
  install(app) {
    app.component('iconProvider', Provider);
    app.component('iconFormatBold', FormatBold);
    app.component('iconFormatItalic', FormatItalic);
    app.component('iconFormatQuoteClose', FormatQuoteClose);
    app.component('iconLinkVariant', LinkVariant);
    app.component('iconFileImage', FileImage);
    app.component('iconTable', Table);
    app.component('iconFormatListNumbers', FormatListNumbers);
    app.component('iconFormatListBulleted', FormatListBulleted);
    app.component('iconFormatSize', FormatSize);
    app.component('iconFormatStrikethrough', FormatStrikethrough);
    app.component('iconStatusBar', StatusBar);
    app.component('iconNavigationBar', NavigationBar);
    app.component('iconSidePreview', SidePreview);
    app.component('iconEye', Eye);
    app.component('iconSettings', Settings);
    app.component('iconFilePlus', FilePlus);
    app.component('iconFileMultiple', FileMultiple);
    app.component('iconFolderPlus', FolderPlus);
    app.component('iconDelete', Delete);
    app.component('iconClose', Close);
    app.component('iconPen', Pen);
    app.component('iconTarget', Target);
    app.component('iconArrowLeft', ArrowLeft);
    app.component('iconHelpCircle', HelpCircle);
    app.component('iconToc', Toc);
    app.component('iconLogin', Login);
    app.component('iconLogout', Logout);
    app.component('iconSync', Sync);
    app.component('iconSyncOff', SyncOff);
    app.component('iconUpload', Upload);
    app.component('iconViewList', ViewList);
    app.component('iconDownload', Download);
    app.component('iconCodeTags', CodeTags);
    app.component('iconCodeBraces', CodeBraces);
    app.component('iconOpenInNew', OpenInNew);
    app.component('iconInformation', Information);
    app.component('iconAlert', Alert);
    app.component('iconSignalOff', SignalOff);
    app.component('iconFolder', Folder);
    app.component('iconScrollSync', ScrollSync);
    app.component('iconPrinter', Printer);
    app.component('iconUndo', Undo);
    app.component('iconRedo', Redo);
    app.component('iconContentSave', ContentSave);
    app.component('iconMessage', Message);
    app.component('iconHistory', History);
    app.component('iconDatabase', Database);
    app.component('iconMagnify', Magnify);
    app.component('iconFormatListChecks', FormatListChecks);
    app.component('iconCheckCircle', CheckCircle);
    app.component('iconContentCopy', ContentCopy);
    app.component('iconKey', Key);
    app.component('iconDotsHorizontal', DotsHorizontal);
    app.component('iconSeal', Seal);
    app.component('iconChevronUp', ChevronUp);
    app.component('iconChevronDown', ChevronDown);
    app.component('iconLanguageMarkdown', LanguageMarkdown);
    app.component('iconLanguageHtml5', LanguageHtml5);
    app.component('iconMath', Math_);
    app.component('iconSitemap', Sitemap);
    app.component('iconHorizontalRule', HorizontalRule);
    app.component('iconMarker', Marker);
    app.component('iconFootnote', Footnote);
    app.component('iconFormatSubscript', FormatSubscript);
    app.component('iconFormatSuperscript', FormatSuperscript);
    app.component('iconCodeInline', CodeInline);
    app.component('iconMusicNote', MusicNote);
    app.component('iconAutoFix', AutoFix);
    app.component('iconCalendar', Calendar);
    app.component('iconCaseSensitiveAlt', CaseSensitiveAlt);
    app.component('iconSortAlphabetical', SortAlphabetical);
    app.component('iconOmega', Omega);
    app.component('iconLinkBracket', LinkBracket);
    app.component('iconLinkPaste', LinkPaste);
    app.component('iconFrontmatter', Frontmatter);
  },
};
