<template>
  <div class="preview">
    <div class="preview__inner-1" @click="onClick" @scroll="onScroll">
      <div class="preview__inner-2" :style="{padding: styles.previewPadding}">
      </div>
      <div class="gutter" :style="{left: styles.previewGutterLeft + 'px'}">
        <comment-list v-if="styles.previewGutterWidth"></comment-list>
        <preview-new-discussion-button v-if="!isCurrentTemp"></preview-new-discussion-button>
      </div>
    </div>
    <div v-if="!styles.showEditor" class="preview__corner">
      <button class="preview__button button" @click="toggleEditor(true)" v-title="'Edit file'">
        <icon-pen></icon-pen>
      </button>
    </div>
  </div>
</template>

<script>
import { mapState as mapPiniaState, mapActions as mapPiniaActions } from 'pinia';
import CommentList from './gutters/CommentList';
import PreviewNewDiscussionButton from './gutters/PreviewNewDiscussionButton';
import editorSvc from '../services/editorSvc';
import { useFileStore } from '../stores/file';
import { useDataStore } from '../stores/data';
import { useLayoutStore } from '../stores/layout';
import { useDiscussionStore } from '../stores/discussion';

const appUri = `${window.location.protocol}//${window.location.host}`;

// Match scrollSync's SCROLL_OFFSET so an anchor jump lands the heading
// ~20px below the top edge and scroll-sync doesn't immediately nudge it.
const SCROLL_OFFSET = 20;

// github-slugger v2's slug algorithm (lowercase, strip punctuation,
// whitespace -> hyphen). StackEdit slugs headings with Pandoc
// `auto_identifiers` (`markdownItAnchor`), which strips everything up
// to the first letter -- so `## 1. Foo` becomes `id="foo"`. TOCs
// generated by GitHub / VS Code / Typora keep the number (`#1-foo`),
// so the href never matches the Pandoc id. `resolveAnchorTarget`
// falls back to re-deriving each heading's GitHub slug and matching
// against that. The two Unicode-punctuation blocks (General
// Punctuation U+2000-U+206F -- em/en dashes, curly quotes;
// Supplemental Punctuation U+2E00-U+2E7F) are built via fromCharCode
// so the source stays ASCII (no `no-irregular-whitespace` from a
// literal U+2000). github-slugger does NOT strip hyphens.
const uniPunct = new RegExp(
  `[${String.fromCharCode(0x2000)}-${String.fromCharCode(0x206F)}`
  + `${String.fromCharCode(0x2E00)}-${String.fromCharCode(0x2E7F)}]`,
  'g',
);
const asciiPunct = /['!"#$%&()*+,./:;<=>?@[\]^`{|}~\\]/g;
function githubSlugBase(text) {
  return text
    .trim()
    .toLowerCase()
    .replace(uniPunct, '')
    .replace(asciiPunct, '')
    .replace(/\s/g, '-');
}

export default {
  components: {
    CommentList,
    PreviewNewDiscussionButton,
  },
  data: () => ({
    previewTop: true,
  }),
  computed: {
    ...mapPiniaState(useFileStore, [
      'isCurrentTemp',
    ]),
    ...mapPiniaState(useLayoutStore, [
      'styles',
    ]),
  },
  methods: {
    ...mapPiniaActions(useDataStore, [
      'toggleEditor',
    ]),
    onClick(evt) {
      let elt = evt.target;
      while (elt && elt !== this.$el) {
        // In-page fragment link (e.g. a Table of Contents entry
        // `[Section](#section)`). Handle it ourselves: the browser
        // default would write `#section` into `window.location.hash`,
        // which StackEdit uses for its own query-param state (see
        // utils.ts `queryParams`), so it never scrolls.
        if (elt.tagName === 'A') {
          const rawHref = elt.getAttribute('href');
          if (rawHref && rawHref.charAt(0) === '#' && rawHref.length > 1) {
            evt.preventDefault();
            this.scrollToAnchor(decodeURIComponent(rawHref.slice(1)));
            return;
          }
        }
        if (elt.href && elt.href.match(/^https?:\/\//)
          && (!elt.hash || elt.href.slice(0, appUri.length) !== appUri)) {
          evt.preventDefault();
          const wnd = window.open(elt.href, '_blank');
          wnd.focus();
          return;
        }
        elt = elt.parentNode;
      }
    },
    resolveAnchorTarget(previewElt, id) {
      // 1. Exact element id -- StackEdit-native / Pandoc-slug TOCs.
      let target;
      try {
        target = previewElt.querySelector(`#${CSS.escape(id)}`);
      } catch (e) {
        target = undefined;
      }
      if (target) {
        return target;
      }
      target = Array.from(previewElt.querySelectorAll('[id]'))
        .find(el => el.id === id);
      if (target) {
        return target;
      }

      // 2. GitHub-slug fallback -- re-derive each heading's GitHub
      //    slug (with github-slugger's `-N` dedup) and match the
      //    requested fragment against it. Covers TOCs generated by
      //    GitHub / VS Code / Typora against Pandoc-slugged headings.
      const headings = Array.from(
        previewElt.querySelectorAll('h1,h2,h3,h4,h5,h6'),
      );
      const occurrences = Object.create(null);
      let match;
      headings.forEach((heading) => {
        const base = githubSlugBase(heading.textContent || '');
        let slug = base;
        if (occurrences[base] !== undefined) {
          occurrences[base] += 1;
          slug = `${base}-${occurrences[base]}`;
        } else {
          occurrences[base] = 0;
        }
        if (!match && slug === id) {
          match = heading;
        }
      });
      if (match) {
        return match;
      }

      // 3. Last resort: case-insensitive heading-text match.
      const wanted = id.replace(/[-_]+/g, ' ').trim().toLowerCase();
      return headings.find(
        h => (h.textContent || '').trim().toLowerCase() === wanted,
      );
    },
    scrollToAnchor(id) {
      const scrollerElt = this.$el.querySelector('.preview__inner-1');
      const previewElt = this.$el.querySelector('.preview__inner-2');
      if (!scrollerElt || !previewElt || !id) {
        return;
      }
      const target = this.resolveAnchorTarget(previewElt, id);
      if (!target) {
        return;
      }

      // Drive BOTH editor and preview from the section map in the same
      // tick -- exactly what the TOC sidebar (Toc.vue) does. Scrolling
      // only the preview leaves the editor stale, and scroll-sync's
      // editor->preview projection then yanks the preview back toward
      // the stale editor position (very visible on long docs / deep
      // sections). Setting both to consistent offsets keeps sync from
      // fighting the jump.
      const ctx = editorSvc.previewCtxMeasured || editorSvc.previewCtx;
      const list = ctx && ctx.sectionDescList;
      const sectionDesc = list
        && list.find(s => s.previewElt && s.previewElt.contains(target));
      if (sectionDesc
        && editorSvc.editorElt && editorSvc.editorElt.parentNode) {
        const offsetInSection = target.getBoundingClientRect().top
          - sectionDesc.previewElt.getBoundingClientRect().top;
        const posInSection = Math.max(0, Math.min(1,
          offsetInSection / (sectionDesc.previewDimension.height || 1)));
        const editorScrollTop = sectionDesc.editorDimension.startOffset
          + (sectionDesc.editorDimension.height * posInSection);
        const previewScrollTop = (sectionDesc.previewDimension.startOffset
          + (sectionDesc.previewDimension.height * posInSection))
          - SCROLL_OFFSET;
        editorSvc.editorElt.parentNode.scrollTop = Math.max(0, Math.floor(editorScrollTop));
        scrollerElt.scrollTop = Math.max(0, Math.floor(previewScrollTop));
        return;
      }

      // Fallback (no section map yet): instant element scroll. Instant
      // rather than smooth so a long animation can't feed scroll-sync.
      const top = (scrollerElt.scrollTop + target.getBoundingClientRect().top)
        - scrollerElt.getBoundingClientRect().top - SCROLL_OFFSET;
      scrollerElt.scrollTop = Math.max(0, top);
    },
    onScroll(evt) {
      this.previewTop = evt.target.scrollTop < 10;
    },
  },
  mounted() {
    const previewElt = this.$el.querySelector('.preview__inner-2');
    const onDiscussionEvt = cb => (evt) => {
      let elt = evt.target;
      while (elt && elt !== previewElt) {
        if (elt.discussionId) {
          cb(elt.discussionId);
          return;
        }
        elt = elt.parentNode;
      }
    };

    const classToggler = toggle => (discussionId) => {
      Array.from(previewElt.getElementsByClassName(`discussion-preview-highlighting--${discussionId}`))
        .forEach(elt => elt.classList.toggle('discussion-preview-highlighting--hover', toggle));
      Array.from(document.getElementsByClassName(`comment--discussion-${discussionId}`))
        .forEach(elt => elt.classList.toggle('comment--hover', toggle));
    };

    previewElt.addEventListener('mouseover', onDiscussionEvt(classToggler(true)));
    previewElt.addEventListener('mouseout', onDiscussionEvt(classToggler(false)));
    previewElt.addEventListener('click', onDiscussionEvt((discussionId) => {
      useDiscussionStore().setCurrentDiscussionId(discussionId);
    }));

    this.$watch(
      () => useDiscussionStore().currentDiscussionId,
      (discussionId, oldDiscussionId) => {
        if (oldDiscussionId) {
          previewElt.querySelectorAll(`.discussion-preview-highlighting--${oldDiscussionId}`)
            .forEach(elt => elt.classList.remove('discussion-preview-highlighting--selected'));
        }
        if (discussionId) {
          previewElt.querySelectorAll(`.discussion-preview-highlighting--${discussionId}`)
            .forEach(elt => elt.classList.add('discussion-preview-highlighting--selected'));
        }
      },
    );
  },
};
</script>

<style lang="scss">
@use '../styles/variables.scss' as *;

.preview,
.preview__inner-1 {
  position: absolute;
  width: 100%;
  height: 100%;
}

.preview__inner-1 {
  overflow: auto;
}

.preview__inner-2 {
  margin: 0;
}

.preview__inner-2 > :first-child > :first-child {
  margin-top: 0;
}

$corner-size: 110px;

.preview__corner {
  position: absolute;
  top: 0;
  right: 0;

  &::before {
    content: '';
    position: absolute;
    right: 0;
    border-top: $corner-size solid rgba(0, 0, 0, 0.075);
    border-left: $corner-size solid transparent;
    pointer-events: none;

    .app--dark & {
      border-top-color: rgba(255, 255, 255, 0.075);
    }
  }
}

.preview__button {
  position: absolute;
  top: 15px;
  right: 15px;
  width: 40px;
  height: 40px;
  padding: 5px;
  color: rgba(0, 0, 0, 0.25);

  .app--dark & {
    color: rgba(255, 255, 255, 0.25);
  }

  &:active,
  &:focus,
  &:hover {
    color: rgba(0, 0, 0, 0.33);
    background-color: transparent;

    .app--dark & {
      color: rgba(255, 255, 255, 0.33);
    }
  }
}
</style>
